// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TS.Data.Context;

#nullable disable

namespace TS.Data.Migrations
{
    [DbContext(typeof(TSContext))]
    [Migration("20240111193037_AddRefreshToken")]
    partial class AddRefreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TS.Model.Models.Cartela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("CompraAprovada")
                        .HasColumnType("bit");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("PremioId")
                        .HasColumnType("int");

                    b.Property<int>("PrimeiroNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuartoNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuintoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SegundoNumero")
                        .HasColumnType("int");

                    b.Property<bool>("Sorteada")
                        .HasColumnType("bit");

                    b.Property<int>("TerceiroNumero")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PremioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cartela");
                });

            modelBuilder.Entity("TS.Model.Models.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("DataEnvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecimoNumero")
                        .HasColumnType("int");

                    b.Property<int>("NonoNumero")
                        .HasColumnType("int");

                    b.Property<int>("OitavoNumero")
                        .HasColumnType("int");

                    b.Property<int>("PrimeiroNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuartoNumero")
                        .HasColumnType("int");

                    b.Property<int>("QuintoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SegundoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SetimoNumero")
                        .HasColumnType("int");

                    b.Property<int>("SextoNumero")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TerceiroNumero")
                        .HasColumnType("int");

                    b.Property<double>("ValorPremio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Premio");
                });

            modelBuilder.Entity("TS.Model.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("TS.Model.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("IndentityId")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("TS.Model.Models.Cartela", b =>
                {
                    b.HasOne("TS.Model.Models.Premio", "Premio")
                        .WithMany("Cartelas")
                        .HasForeignKey("PremioId")
                        .IsRequired();

                    b.HasOne("TS.Model.Models.Usuario", "Usuario")
                        .WithMany("Cartelas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Premio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TS.Model.Models.Premio", b =>
                {
                    b.Navigation("Cartelas");
                });

            modelBuilder.Entity("TS.Model.Models.Usuario", b =>
                {
                    b.Navigation("Cartelas");
                });
#pragma warning restore 612, 618
        }
    }
}
